---
name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code.
      uses: actions/checkout@v2
    - name: Build PDFs.
      uses: xu-cheng/latex-action@v2
      with:
        root_file: |
          Einzug.tex
          Aufnahmeantrag_aktiv.tex
          Aufnahmeantrag_foerder_nat.tex
          Aufnahmeantrag_foerder_jur.tex
    - name: Check PDFs exist.
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "Einzug.pdf, Aufnahmeantrag_foerder_jur.pdf, Aufnahmeantrag_aktiv.pdf, Aufnahmeantrag_foerder_nat.pdf"
    - name: PDFs exist.
      if: steps.check_files.outputs.files_exists == 'true'
      run: echo All PDFs built successfully!
