---
name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker-practice/actions-setup-docker@v1
    - name: Build PDFs.
      run: make
    - name: Check PDFs exist.
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "Einzug.pdf, Aufnahmeantrag_foerder_jur.pdf, Aufnahmeantrag_aktiv.pdf, Aufnahmeantrag_foerder_nat.pdf"
    - name: PDFs exist.
      if: steps.check_files.outputs.files_exists == 'true'
      run: echo All PDFs built successfully!
